// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppCalendar: typeof import('./src/components/AppCalendar.vue')['default']
    AppCalendarCurrentTime: typeof import('./src/components/AppCalendarCurrentTime.vue')['default']
    AppCalendarDateController: typeof import('./src/components/AppCalendarDateController.vue')['default']
    AppCalendarDays: typeof import('./src/components/AppCalendarDays.vue')['default']
    AppCalendarEvent: typeof import('./src/components/AppCalendarEvent.vue')['default']
    EditableList: typeof import('./src/components/EditableList.vue')['default']
    EditableValue: typeof import('./src/components/EditableValue.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    MenuItem: typeof import('./src/components/MenuItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowAppointments: typeof import('./src/components/ShowAppointments.vue')['default']
  }
}

export {}
